# 🚨 CRITICAL: NON-NEGOTIABLE BRANCH PROTECTION RULES
# ALL TESTS MUST PASS BEFORE ALLOWING ANY MERGE TO MAIN BRANCH
# This prevents CI build failures by ensuring tests pass before any deployment

# Branch Protection Rules for main branch
# These rules ensure that ALL tests must pass before any code can be merged
# This is a non-negotiable requirement to prevent CI build failures

branch_protection_rules:
  - pattern: "main"
    required_status_checks:
      strict: true  # Require branches to be up to date before merging
      contexts:
        - "🧪 Comprehensive Test Suite (REQUIRED)"  # comprehensive-test-suite job
        - "🔗 Integration Tests (REQUIRED)"         # integration-tests job  
        - "📊 Coverage Analysis (REQUIRED)"        # coverage-analysis job
    enforce_admins: true  # Apply rules to admins too
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null  # No restrictions on who can push
    allow_force_pushes: false  # Prevent force pushes
    allow_deletions: false  # Prevent branch deletion
    block_creations: false  # Allow branch creation
    required_conversation_resolution: true  # Require conversation resolution

  - pattern: "develop"
    required_status_checks:
      strict: true
      contexts:
        - "🧪 Comprehensive Test Suite (REQUIRED)"
        - "🔗 Integration Tests (REQUIRED)"
        - "📊 Coverage Analysis (REQUIRED)"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions: null
    allow_force_pushes: false
    allow_deletions: false
    block_creations: false
    required_conversation_resolution: true

# Required Status Check Names (must match job names in workflow):
# 1. "🧪 Comprehensive Test Suite (REQUIRED)" - comprehensive-test-suite
# 2. "🔗 Integration Tests (REQUIRED)" - integration-tests  
# 3. "📊 Coverage Analysis (REQUIRED)" - coverage-analysis

# These status checks MUST be configured in GitHub repository settings:
# Settings > Branches > Branch protection rules > main > Require status checks to pass before merging
# Add all three status check names above as required checks
