codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "tests/"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "venv/"
  - ".venv/"
  - "env/"
  - ".env/"
  - "*.egg-info/"
  - "build/"
  - "dist/"
  - ".pytest_cache/"
  - ".coverage"
  - "htmlcov/"
  - "coverage.xml"

github_checks:
  annotations: true
