name: Deploy to Fly.io

# ⚠️  CRITICAL: This workflow only runs after ALL tests pass with coverage
# The comprehensive test suite must complete successfully before deployment
# This ensures the deployed service works exactly like local development

on:
  workflow_run:
    workflows: ["Comprehensive Test Suite"]
    types:
      - completed
    branches: [main]

jobs:
  # CRITICAL: This job only runs after comprehensive test suite passes
  # All tests must run with coverage and pass before deployment
  # The e2e test validates the complete user journey
  # The post-deploy test validates the deployed service works correctly
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Flyctl
      uses: superfly/flyctl-actions/setup-flyctl@master
      
    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: |
        flyctl deploy --remote-only
        
    - name: Health check
      run: |
        sleep 30
        curl -f https://tdg-mvp.fly.dev/health || exit 1
        
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Run post-deployment tests
      run: |
        sleep 10  # Give the deployment a moment to fully stabilize
        python -m pytest tests/test_post_deploy.py::test_deployed_service_complete_user_experience -v -s --log-cli-level=INFO